version: 2

jobs:
  test:
    docker:
      - image: "circleci/node:10-browsers"
    steps:
      - checkout
      - run: yarn
      - run: yarn test

workflows:
  version: 2
  test:
    jobs:
      - test
